---
title       : Emotional Engagement Study        
subtitle    : Emotion determines intent, preference and future behavior
author      : Stephen Trask, MT
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
--- 

### Emotion influences 95% of consumer behavior

* When rational and emotional thoughts are at odds, emotion wins
* Emotion drives preference and memory
* Emotionally charged events and products are remembered better
* Positive memories contain more contextual details 

--- .class1 bg:yellow 

### Emotions cause physiologic changes 

* The change in background probably suprised you, which can cause many of the following...

        1. Expressions emerge on a face
        2. Heart rate increases, pupils dilate
        3. Skin conductance changes and muscles contract
        4. Most changes happen without conscious awareness

--- .class #id 

### Quantifying these changes provides insight

* These biometrics are surrogate markers for engagement
* The process finds correlations
* The output is a prediction of future behaviors
* Clients can make better decisions to impact ROI

--- .class #id 

### So you can learn, I am sharing

* Example visualizations from a recent study are in the App I created

The same app will allow you to estimate the costs for your own study.  Just enter the variables we ask for and an estimate will be provided.



Note: This deck was built with Slidify and R,  therefore you could have written live code in this.
For example... Say you want to generate a random number between 5.0 and 7.5
```r
x1 <- runif(1, 5.0, 7.5)
x1
[1] 7.438408
```

